### ISSUE TITLE
origin conflict when converting from grid map to occupancy grid

### ISSUE THREAD

**Issue by bit-pirate** [ethz-asl/grid_map#33]
I started playing around with this library and as a first test I implemented a "round trip conversion": `nav_msgs::OccupancyGrid`-> `grid_map_msgs::GridMap` -> `grid_map::GridMap` -> `nav_msgs::OccupancyGrid`.

The first conversion is done by my own implementation (couldn't find an implementation in this library), the second is using `grid_map::GridMapRosConverter::fromMessage` and the last `grid_map::GridMapRosConverter::toOccupancyGrid`. 

The result looks fine, except 1) the costmap is rotated and 2) there is an offset in the origin's position.

Starting with the **first issue**, the original origin's quaternion is:

```
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
```

The quaternion of the intermediate grid map is the same:

```
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
```

But the final quaternion is different:

```
    orientation: 
      x: 0.0
      y: 0.0
      z: 1.0
      w: 0.0
```

Looking at the code, I found [this part](https://github.com/ethz-asl/grid_map/blob/master/grid_map/src/GridMapRosConverter.cpp#L204-L207):

```
occupancyGrid.info.origin.orientation.x = 0.0;
occupancyGrid.info.origin.orientation.y = 0.0;
occupancyGrid.info.origin.orientation.z = 1.0;  // yes, this is correct.
occupancyGrid.info.origin.orientation.w = 0.0;
```

I don't understand why this change is necessary. Could someone please explain?

Looking at the **second issue** about the position offset the situation is similar. The original origin position in my example is:

```
    position: 
      x: -50.0
      y: -50.0
      z: 0.0
```

The position of the grid map's origin is the same. But during the conversion into a occupancy grid the origin is shifted/adjusted to:

```
    position: 
      x: 7.45058059692e-07
      y: 7.45058059692e-07
      z: 0.0
```

The reference frame for the origin of the occupancy grid in ROS (e.g. when published by `move_base`) seems to be one of the corners. When looking into the [conversion code ([part 1](https://github.com/ethz-asl/grid_map/blob/master/grid_map/src/GridMapRosConverter.cpp#L200), [part 2](https://github.com/ethz-asl/grid_map/blob/master/grid_map_core/src/GridMapMath.cpp#L161-L168)) it seems to be assumed that the reference frame is the centre. What's the reason behind this?
